import { afterEach, describe, expect, it } from 'vitest';
import { POST } from '@/app/api/discover/route';

const originalAnthropicKey = process.env.ANTHROPIC_API_KEY;

function restoreAnthropicKey() {
  if (originalAnthropicKey === undefined) {
    delete process.env.ANTHROPIC_API_KEY;
  } else {
    process.env.ANTHROPIC_API_KEY = originalAnthropicKey;
  }
}

function requestWithMessages(messages: Array<{ role: 'user' | 'assistant'; content: string }>) {
  return new Request('http://localhost/api/discover', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-forwarded-for': `discover-chat-test-${crypto.randomUUID()}`,
    },
    body: JSON.stringify({ messages }),
  });
}

afterEach(() => {
  restoreAnthropicKey();
});

describe('discover chat route', () => {
  it('accepts long website research context generated by the discover UI', async () => {
    delete process.env.ANTHROPIC_API_KEY;

    const researchContext = `[Research Context — use to inform responses, do not repeat verbatim]\n\n${'Company research, value-chain activity, owner, metric, adoption, and controls. '.repeat(140)}`;
    expect(researchContext.length).toBeGreaterThan(4000);

    const response = await POST(
      requestWithMessages([
        { role: 'user', content: researchContext },
        { role: 'assistant', content: 'What is the biggest operational constraint?' },
        { role: 'user', content: 'Sales follow-up is inconsistent after the first call.' },
      ]),
    );

    expect(response.status).toBe(200);
    await expect(response.json()).resolves.toEqual(
      expect.objectContaining({
        content: expect.stringContaining('currently unavailable'),
      }),
    );
  });

  it('keeps ordinary visitor messages capped', async () => {
    delete process.env.ANTHROPIC_API_KEY;

    const response = await POST(
      requestWithMessages([{ role: 'user', content: 'Ordinary visitor message. '.repeat(220) }]),
    );

    expect(response.status).toBe(400);
    await expect(response.json()).resolves.toEqual(
      expect.objectContaining({
        content: 'Please send a valid discovery conversation.',
      }),
    );
  });
});
