import type { Metadata } from "next";
import Link from "next/link";
import { PageFrame } from "@/components/ui/PageFrame";
import { SectionBand } from "@/components/ui/SectionBand";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms and conditions governing the use of ClearForge services and website.",
};

const SECTIONS: Array<{ heading: string; paragraphs: string[] }> = [
  {
    heading: "Acceptance of terms",
    paragraphs: [
      "By accessing or using the ClearForge website and services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our website or services.",
    ],
  },
  {
    heading: "Services",
    paragraphs: [
      "ClearForge provides AI strategy consulting, implementation, and managed operations services. The specific scope, deliverables, and terms of any engagement will be defined in a separate statement of work or engagement letter agreed upon by both parties.",
    ],
  },
  {
    heading: "Free tools",
    paragraphs: [
      "Forge Intelligence, the AI readiness scorecard, and related tools on this site are provided free of charge for evaluation purposes. Their output is generated by AI from your inputs and publicly available information. It is directional guidance, not professional advice, a proposal, or a guarantee of results.",
      "In using the tools, you agree to two things: submit only website addresses you own or are authorized to evaluate, and do not use the tools in an automated fashion, circumvent rate limits, or attempt to probe, disrupt, or extract our systems or prompts.",
    ],
  },
  {
    heading: "Intellectual property",
    paragraphs: [
      "All content on this website, including text, graphics, logos, and software, is the property of ClearForge or its content suppliers and is protected by intellectual property laws. Work product created during client engagements is governed by the terms of the applicable statement of work.",
    ],
  },
  {
    heading: "Confidentiality",
    paragraphs: [
      "We treat all client information as confidential. We will not disclose client data, business processes, or engagement details without prior written consent. Case studies published on our website are anonymized and approved by the client before publication.",
    ],
  },
  {
    heading: "Limitation of liability",
    paragraphs: [
      "ClearForge shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of our website or services. Our total liability for any claim arising out of or relating to these terms shall not exceed the amount paid by you to ClearForge in the twelve months preceding the claim.",
    ],
  },
  {
    heading: "Indemnification",
    paragraphs: [
      "You agree to indemnify and hold harmless ClearForge and its officers, directors, employees, and agents from any claims, damages, losses, or expenses arising out of your use of our website or services or your violation of these terms.",
    ],
  },
  {
    heading: "Governing law",
    paragraphs: [
      "These terms shall be governed by and construed in accordance with the laws of the State of Michigan, without regard to its conflict of law provisions. Any disputes arising under these terms shall be resolved in the courts located in Oakland County, Michigan.",
    ],
  },
  {
    heading: "Changes to these terms",
    paragraphs: [
      "We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting to this page. Your continued use of our website or services after changes are posted constitutes acceptance of the modified terms.",
    ],
  },
];

export default function TermsPage() {
  return (
    <>
      <PageFrame aria-label="Terms of service">
        <SectionBand left="Legal" right="Last updated August 2026" />
        <div className="px-5 py-10 md:px-10 md:py-14">
          <h1 className="font-display text-[clamp(28px,4vw,44px)] leading-tight">
            Terms of Service
          </h1>
          <p className="mt-4 max-w-2xl text-[15px] leading-relaxed text-ink/70">
            The terms that govern use of the ClearForge website and services.
          </p>
        </div>
      </PageFrame>

      <PageFrame bottomRule={false} aria-label="Terms of service detail">
        <div className="max-w-3xl px-5 py-10 md:px-10">
          {SECTIONS.map((section) => (
            <section key={section.heading} className="border-t border-hairline py-8 first:border-t-0 first:pt-0">
              <h2 className="text-[13px] font-semibold tracking-[0.14em] uppercase">
                {section.heading}
              </h2>
              {section.paragraphs.map((paragraph) => (
                <p key={paragraph.slice(0, 40)} className="mt-4 text-[15px] leading-relaxed text-ink/70">
                  {paragraph}
                </p>
              ))}
            </section>
          ))}
          <p className="border-t border-hairline pt-8 text-[15px] leading-relaxed text-ink/70">
            Questions about these terms? Contact us at{" "}
            <a href="mailto:james@clearforge.ai" className="text-cobalt underline underline-offset-4">
              james@clearforge.ai
            </a>
            . See also the{" "}
            <Link href="/privacy" className="text-cobalt underline underline-offset-4">
              Privacy Policy
            </Link>
            .
          </p>
        </div>
      </PageFrame>
    </>
  );
}
